/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib_projekt;

import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author David
 */
public class GeAgentAdminstatus extends javax.swing.JFrame {

    private InfDB idb;
    private int AgentID;

    /**
     * Creates new form GeAgentAdminstatus
     */
    public GeAgentAdminstatus(InfDB idb) {
        initComponents();
        this.idb = idb;
        this.AgentID = AgentID;
        fyllAgentNamn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxValjAgent = new javax.swing.JComboBox<>();
        lblValjAgent = new javax.swing.JLabel();
        lbValjStatus = new javax.swing.JLabel();
        lblAndraAdminStatus = new javax.swing.JLabel();
        btnGodkann = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTillbaka2 = new javax.swing.JButton();
        lblAgentHarStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBoxValjAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxValjAgentActionPerformed(evt);
            }
        });

        lblValjAgent.setText("Välj Agent");

        lblAndraAdminStatus.setText("Ändra Administratörstatus");

        btnGodkann.setText("Godkänn ändring");
        btnGodkann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGodkannActionPerformed(evt);
            }
        });

        btnTillbaka2.setText("Tillbaka");
        btnTillbaka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbaka2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblAndraAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(btnTillbaka2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblAgentHarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGodkann)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbValjStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAndraAdminStatus)
                    .addComponent(btnTillbaka2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValjAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAgentHarStatus)
                .addGap(18, 18, 18)
                .addComponent(lbValjStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGodkann)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fyllAgentNamn() {
        try {
            // SQL-fråga för att hämta Plats_ID och Benamning från plats-tabellen
            String fraga = "SELECT Agent_ID, Namn FROM agent;";
            // Utför SQL-frågan och få resultatet
            var resultat = idb.fetchRows(fraga);
            // Iterera över varje rad i resultatet
            for (HashMap<String, String> rad : resultat) {
                // Hämta Plats_ID och Benamning från raden
                String AgentIdStr = rad.get("Agent_ID");
                String AgentNamn = rad.get("Namn");

                // Kontrollera om Plats_ID är inte null
                if (AgentIdStr != null) {
                    // Lägg till Benamning i dropdown-menyn
                    ComboBoxValjAgent.addItem(AgentNamn);
                }
            }
        } catch (InfException ex) {
            // Visa felmeddelande om något går fel med databasen
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }


    private void btnGodkannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGodkannActionPerformed
        try {
            String valtAgentNamn = ComboBoxValjAgent.getSelectedItem().toString();

            String fragaAgentID = "SELECT Agent_ID FROM agent WHERE Namn = '" + valtAgentNamn + "'";
            String AgentensID = idb.fetchSingle(fragaAgentID);
            String kollaAdminStatus = "Select administrator from agent where agent_ID =" + AgentensID;
            String svarAdminStatus = idb.fetchSingle(kollaAdminStatus);
            String nyStatus;
            
            if(svarAdminStatus.equals("J")){
                nyStatus = "N";
            }else{
                nyStatus = "J";
            }
          
            if (AgentensID != null) {
                // Uppdatera adminstatus för den valda agenten i databasen
                String updateFraga = "UPDATE agent SET Administrator = '" + nyStatus + "' WHERE Agent_ID = " + AgentensID;
                idb.update(updateFraga);
            }

// Uppdatera status i lbAgentStatus
            JOptionPane.showMessageDialog(null, "Ändring Lyckades!");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel med SQL-frågan!");
            System.out.println("Internt felmeddelande: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGodkannActionPerformed

    private void btnTillbaka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbaka2ActionPerformed
        // TODO add your handling code here:
        EfterInloggAdmin nytt = new EfterInloggAdmin();
        GeAgentAdminstatus.this.setVisible(false);
        nytt.setVisible(true);
    }//GEN-LAST:event_btnTillbaka2ActionPerformed

    private void ComboBoxValjAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxValjAgentActionPerformed
        String valtAgentNamn = ComboBoxValjAgent.getSelectedItem().toString();

        if (valtAgentNamn != null)
        try {
            // Hämta aktuell adminstatus för den valda agenten
            String fraga = "SELECT Administrator FROM agent WHERE Namn = '" + valtAgentNamn + "'";
            var aktuellAdminStatus = idb.fetchSingle(fraga);

            if ("N".equals(aktuellAdminStatus)) {
                lbValjStatus.setText("Vill du ändra adminstatus för " + valtAgentNamn + " till adminstrator");

            } else {
                lbValjStatus.setText("Vill du ta bort adminstatus för " + valtAgentNamn);

            }
        } catch (InfException Fel) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + Fel.getMessage());
        }

    }//GEN-LAST:event_ComboBoxValjAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            InfDB idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            GeAgentAdminstatus GeAgentAdminstatusFrame = new GeAgentAdminstatus(idb);

            GeAgentAdminstatusFrame.setSize(551, 301);
            GeAgentAdminstatusFrame.setVisible(true);
        } catch (InfException Fel) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + Fel.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxValjAgent;
    private javax.swing.JButton btnGodkann;
    private javax.swing.JButton btnTillbaka2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbValjStatus;
    private javax.swing.JLabel lblAgentHarStatus;
    private javax.swing.JLabel lblAndraAdminStatus;
    private javax.swing.JLabel lblValjAgent;
    // End of variables declaration//GEN-END:variables
}
